name: sroa_users_function
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  dart_appwrite: ^19.2.1

dev_dependencies:
  test: ^1.25.6
